# User API
POST http://localhost:5000/users/login
Content-type: application/json

{
  "email": "visitor@mail.com",
  "password" : "password123"
}

###
POST http://localhost:5000/users/login
Content-type: application/json

{
  "email": "employee@mail.com",
  "password" : "password123"
}

###
POST http://localhost:5000/users/login
Content-type: application/json

{
  "email": "admin@mail.com",
  "password" : "password123"
}

###
POST http://localhost:5000/users
Content-type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "email": "johndoe1@email.com",
  "password": "password123"
}

###
GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###
GET http://localhost:5000/users/3/statistics
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInJvbGUiOiJhZG1pbiIsImlkIjozLCJpYXQiOjE2NzUxODg3NTEsImV4cCI6MTY3NTE5MjM1MX0.lCzZgvSCvyQm8IY0lS0r-22Q6G1m9DwlMWlQwcx4ge0


###
POST http://localhost:5000/users
Content-type: application/json

{
  "firstname": "Jessy",
  "lastname": "haz",
  "email": "Jessy@mail.com",
  "password": "password123"
}

###
PUT http://localhost:5000/users/4
Content-type: application/json

{
  "firstname": "Mike",
  "lastname": "Mekoui",
  "email": "mouns@gmail.com",
  "password": "password123"
}

###
PUT http://localhost:5000/users/4
Content-Type: application/json

{
  "role": "admin"
}

# Decision API
###
GET http://localhost:5000/decisions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJvbGUiOiJ2aXNpdG9yIiwiaWQiOjEsImlhdCI6MTY3NTE3NzI1NiwiZXhwIjoxNjc1MTgwODU2fQ._6LcYw2DbZDGmACBXFWY0XpnVBKVanE8FwfZ1KrvSDM
###
GET http://localhost:5000/decisions/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInJvbGUiOiJhZG1pbiIsImlkIjozLCJpYXQiOjE2NzUxODg3NTEsImV4cCI6MTY3NTE5MjM1MX0.lCzZgvSCvyQm8IY0lS0r-22Q6G1m9DwlMWlQwcx4ge0
###
DELETE http://localhost:5000/decisions/7

###
PUT http://localhost:5000/decisions/4
Content-Type: application/json

{
  "middle_decision" : "I am the middle decision"
}

